/* -------------------------------
 * PortfolioVARChartGenerator.java
 * -------------------------------
 *
 */

package com.bcfinancial.servlet;

import com.bcfinancial.portfolio.PortfolioCalculatedData;

import java.awt.Color;

import java.io.IOException;
import java.io.OutputStream;
import java.util.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.time.Day;
import org.jfree.data.xy.XYDataset;
import org.jfree.date.MonthConstants;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.RectangleInsets;

import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;

/**
 * A servlet that returns one of three VAR distributions as a PNG image file.  This servlet is
 * referenced in the HTML generated by PortfolioVAR.
 * <P>
 * Three different charts can be generated, controlled by the 'type' parameter.  The possible
 * values are 'growth', 'value' and 'mixed'.
 */
public class PortfolioVARChartGenerator extends HttpServlet {

    /**
     * Default constructor.
     * TODO Phase 4: wire to PortfolioParallelExecutor and a real data source.
     */
    public PortfolioVARChartGenerator() {
    }

    /**
     * Process a GET request.
     * TODO Phase 4: replace stub with real chart generation.
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
        // PortfolioComputeFarmClient (ComputeFarm/Jini) was removed in Phase 2.
        // This servlet will be re-implemented in Phase 4 using PortfolioParallelExecutor.
        response.sendError(HttpServletResponse.SC_NOT_IMPLEMENTED,
                "Chart generation pending Phase 4 redesign");
    }


    /**
     * Creates a chart showing the VAR distribution for the growth portfolio
     *
     * @return a time series chart.
     */
    private JFreeChart createPortfolioVARChart(List list) {
	
        XYSeries s1 = new XYSeries("Return");
	for (int i=0;i<list.size();i++) {
	    s1.add(i,((Double)list.get(i)).doubleValue());
	}
	
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(s1);



        JFreeChart chart = 
	    ChartFactory.createXYLineChart(
	    "Return distribution for portfolio",
	    "Sorted returns",
	    "Return",   // y-axis label
	    dataset,            // data
	    PlotOrientation.VERTICAL,               // orientation
	    true,               // include legand?
	    true,               // generate tooltips?
	    false               // generate URLs?
	    );
    

        chart.setBackgroundPaint(Color.white);

        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint(Color.lightGray);
        plot.setDomainGridlinePaint(Color.white);
        plot.setRangeGridlinePaint(Color.white);
        plot.setAxisOffset(new RectangleInsets(5.0, 5.0, 5.0, 5.0));
        plot.setDomainCrosshairVisible(true);
        plot.setRangeCrosshairVisible(true);
        
        XYLineAndShapeRenderer r = (XYLineAndShapeRenderer)plot.getRenderer();
        if (r instanceof XYLineAndShapeRenderer) {
            XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) r;
            renderer.setBaseShapesVisible(false);

        }
        
        NumberAxis axis = (NumberAxis) plot.getDomainAxis();
        axis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
	
        return chart;
    }


    /*
    private List getGrowthPortfolioVARDistribution() {




     int analysis_year = 1998;
     int analysis_month = 2;
     int analysis_date = 3;
     int analysis_duration = 1;
     int analysis_interval = 90;
    
	Vector symbols = new Vector();
	Vector weights = new Vector();
	Portfolio portfolio = null;
	GregorianCalendar startAnalysisDate = new GregorianCalendar(analysis_year,analysis_month,analysis_date);
	GregorianCalendar endAnalysisDate = (GregorianCalendar)startAnalysisDate.clone();
	endAnalysisDate.add(GregorianCalendar.YEAR, analysis_duration);



	PersistenceManagerImpl epm = new PersistenceManagerImpl(Equity.class);


	symbols.add("slasx");
	symbols.add("mfocx");
	symbols.add("ptrax");
	//	symbols.add("ftbfx");
	//	symbols.add("lmofx");
	//	symbols.add("pavlx");
	symbols.add("usglx");
	symbols.add("jansx");
	symbols.add("fdgfx");
	symbols.add("oakmx");
	symbols.add("ithax");
	symbols.add("sblgx");
	//	symbols.add("omsox");
	symbols.add("phyax");
	symbols.add("flpsx");
	symbols.add("fagix");
	//	symbols.add("pahix");
	symbols.add("wbigx");
	//	symbols.add("psfax");
	symbols.add("fdivx");
	//	symbols.add("fdvix");
	symbols.add("fmilx");
	symbols.add("fresx");
	//	symbols.add("pcrrx");
	//	symbols.add("miqbx");
	//	symbols.add("civvx");


	weights.add(new Double(.07));
	weights.add(new Double(.065));
	weights.add(new Double(.06));
	//	weights.add(new Double(.055));
	//	weights.add(new Double(.055));
	//	weights.add(new Double(.05));
	weights.add(new Double(.048));
	weights.add(new Double(.045));
	weights.add(new Double(.04));
	weights.add(new Double(.04));
	weights.add(new Double(.04));
	weights.add(new Double(.04));
	//	weights.add(new Double(.04));
	weights.add(new Double(.035));
	weights.add(new Double(.035));
	weights.add(new Double(.035));
	//	weights.add(new Double(.035));
	weights.add(new Double(.03));
	//	weights.add(new Double(.03));
	weights.add(new Double(.03));
	//	weights.add(new Double(.03));
	weights.add(new Double(.022));
	weights.add(new Double(.02));
	//	weights.add(new Double(.02));
	//	weights.add(new Double(.015));
	//	weights.add(new Double(.015));


	
	portfolio = new Portfolio(symbols,weights);

	
	List list = portfolio.getSortedReturnDistribution(analysis_interval, startAnalysisDate.getTime(),endAnalysisDate.getTime());
	Collections.sort(list);


	double mean = 0.0;
	double total = 0.0;
	for (int k=0;k<list.size();k++) {
	    total+=((Double)list.get(k)).doubleValue();
	}
	mean = total / list.size();
	System.out.println("mean: "+mean);

	int nn = (1 * list.size())/100;
	int nf = (5 * list.size())/100;

	System.out.println("VAR at 99%: "+list.get(nn));
	System.out.println("VAR at 95%: "+list.get(nf));
	
	return list;

	}
*/




}
