driverClass = "org.mariadb.jdbc.mariadb-java-client"
db = "jdbc:mariadb://mariadb_host:3306/IndependenceFinancial"
dbUser = "admin_user"
dbPassword = "admin_user"
SP500FileName = "src/config/equity_sheets/S&P 500 Companies (Standard and Poor 500).xlsx"
